### ISSUE TITLE
Scripts "not found"

### ISSUE THREAD

**Issue by zensphinx** [paulherron/powermate-hooks#1]
Many thanks for writing these scripts. I have been looking for something like this for some time. 

I would be very grateful for any indications as to what may be happening here. I have a Raspberry Pi 4B and a USB Griffin Powermate. I installed powermate-hooks as per the instructions. The light turns on and off, but nothing else happens. I have not modified the scripts. The result I get is this:

```
fd 3, static brightness is 0, pulse speed is 255, pulse table is 0, pulse asleep is 1, pulse awake is 0
4, 1, 589568The LED pulse settings were changed; code=0x0001, value=0x0008ff00
The LED pulse settings were changed; code=0x0001, value=0x0008ff00
Button was pressed
Warning: unexpected event type; ev->type = 0x0000
Button was released
Pressed on
fd 3, static brightness is 255, pulse speed is 255, pulse table is 0, pulse asleep is 1, pulse awake is 0
4, 1, 589823Warning: unexpected event type; ev->type = 0x0000
sh: 1: ./hooks/press-on.sh: not found
The LED pulse settings were changed; code=0x0001, value=0x0008ffff
Button was rotated 1 units; Offset from start is now 1 units
sh: 1: ./hooks/rotate.sh: not found
Percentage is now 61Warning: unexpected event type; ev->type = 0x0000
Button was rotated 1 units; Offset from start is now 2 units
sh: 1: ./hooks/rotate.sh: not found
Percentage is now 62Warning: unexpected event type; ev->type = 0x0000
Button was rotated 1 units; Offset from start is now 3 units
sh: 1: ./hooks/rotate.sh: not found
...
Percentage is now 59Warning: unexpected event type; ev->type = 0x0000
Button was pressed
Warning: unexpected event type; ev->type = 0x0000
Button was released
Pressed off
fd 3, static brightness is 0, pulse speed is 255, pulse table is 0, pulse asleep is 1, pulse awake is 0
4, 1, 589568Warning: unexpected event type; ev->type = 0x0000
sh: 1: ./hooks/press-off.sh: not found
```
... and so on.

I have been trying to use the Powermate to control the volume (and on press, mute/unmute sound) on my Pi (I use a small, usb-powered speaker which works fine--I can normally control the volume with alsamixer), so your script seems like a good starting point.

Many thanks in advance for any assistance.

**Comment by zensphinx** [comment]
Apparently the powermate-hooks script expected the scripts to be press-off.**default.**sh, press-on.**default.**sh, and rotate.**default.**sh, so I just renamed the scripts and it is now working! Many thanks for your work!

**Comment by paulherron** [comment]
Thanks @zensphinx - glad you got it working. :+1:
